
# tap repositories and their packages

tap homebrew/core
brew aom
brew aribb24
brew autoconf
brew aws-nuke
brew awscli
brew bash
brew brotli
brew ca-certificates
brew cairo
brew cask
brew certifi
brew cffi
brew cjson
brew coreutils
brew cryptography
brew dav1d
brew direnv
brew dotnet
brew dotnet@8
brew emacs
brew exiftool
brew ffmpeg
brew fish
brew flac
brew flux
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gettext
brew giflib
brew glab
brew glib
brew gmp
brew gnutls
brew goenv
brew graphite2
brew harfbuzz
brew helm
brew highway
brew icu4c@76
brew icu4c@77
brew imath
brew jansson
brew jpeg-turbo
brew jpeg-xl
brew kubernetes-cli
brew kustomize
brew lame
brew leptonica
brew libarchive
brew libass
brew libb2
brew libbluray
brew libdeflate
brew libevent
brew libgit2
brew libidn2
brew libmicrohttpd
brew libnghttp2
brew libogg
brew libpng
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libunibreak
brew libunistring
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew little-cms2
brew llvm@19
brew lpeg
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew mbedtls
brew mise
brew monolith
brew mpdecimal
brew mpg123
brew ncurses
brew neovim
brew nettle
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opentofu
brew opus
brew p11-kit
brew pango
brew pcre2
brew pipx
brew pixman
brew pkgconf
brew pycparser
brew pyenv
brew python-packaging
brew python@3.13
brew rav1e
brew readline
brew rename
brew rubberband
brew rust
brew sdl2
brew snappy
brew speex
brew sqlite
brew srt
brew svt-av1
brew telnet
brew tesseract
brew theora
brew tree
brew tree-sitter
brew unbound
brew unibilium
brew usage
brew utf8proc
brew webp
brew wget
brew whalebrew
brew x264
brew x265
brew xmlstarlet
brew xorgproto
brew xvid
brew xz
brew yt-dlp
brew zeromq
brew zimg
brew zstd

tap homebrew/cask
cask anaconda
cask balenaetcher
cask docker
cask dotnet-sdk
cask font-fira-mono-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-meslo-lg-nerd-font
cask iterm2
cask jdownloader

tap grdl/tap
brew git-get

tap nikitabobko/tap
cask aerospace

tap rcmdnk/file
brew brew-file

tap stefansundin/tap
cask vlc-protocol

# App Store applications
appstore 1333542190 1Password 7 (7.9.11)
appstore 1569813296 1Password for Safari (8.10.76)
appstore 1352778147 Bitwarden (2025.4.2)
appstore 442160987 Flycut (1.9.6)
appstore 405399194 Kindle (1.40.3)
appstore 985367838 Microsoft Outlook (16.97)
appstore 966085870 TickTick (6.2.40)
